package it.david.utility;

public enum JobIdEnum {

	    SVILUPPATORE_SOFTWARE,
	    ANALISTA_DATI,
	    DESIGNER_GRAFICO,
	    RESPONSABILE_MARKETING,
	    CONTABILE,
	    COMMERCIALE,
	    ASSISTENTE_AMMINISTRATIVO,
	    RISORSE_UMANE,
	    PROJECT_MANAGER,
	    INGEGNERE_CIVILE,
	    ARCHITETTO,
	    INFERMIERE,
	    MEDICO,
	    AVVOCATO,
	    INSEGNANTE
	}
